### ISSUE TITLE
[Bug]: Build fails with OpenSSL 1.1

### ISSUE THREAD

**Issue by MV-GH** [LemmyNet/lemmy#3981]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

i am trying to build Lemmy on a Debian based distro.

I installed the necessary packages

libpq-dev installs openSSL 1.1.1 which depreciates `EVP_MD_CTX_create`, etc which cause this build to fail I believe

### Steps to Reproduce

1. cargo build
2.
3.

### Technical Details

see stacktrace
 /home/maart/git/lemmy/target/debug/deps/liblemmy_apub-06647d6b9d18a431.rlib(lemmy_apub-06647d6b9d18a431.1k0do7f23fft7p3o.rcgu.o): In function `openssl::sign::Signer::new_intern':
          1k0do7f23fft7p3o:(.text._ZN7openssl4sign6Signer10new_intern17hff6e135d9e25b3c3E+0x28): undefined reference to `EVP_MD_CTX_create'
          1k0do7f23fft7p3o:(.text._ZN7openssl4sign6Signer10new_intern17hff6e135d9e25b3c3E+0x19b): undefined reference to `EVP_MD_CTX_destroy'
          /home/maart/git/lemmy/target/debug/deps/libactivitypub_federation-65bc6a0f9768f0e5.rlib(activitypub_federation-65bc6a0f9768f0e5.activitypub_federation.203ece70cbaa019d-cgu.2.rcgu.o): In function `openssl::sign::Verifier::new_intern':
          activitypub_federation.203ece70cbaa019d-cgu.2:(.text._ZN7openssl4sign8Verifier10new_intern17h3f6201ff9f16f273E+0x28): undefined reference to `EVP_MD_CTX_create'
          activitypub_federation.203ece70cbaa019d-cgu.2:(.text._ZN7openssl4sign8Verifier10new_intern17h3f6201ff9f16f273E+0x19b): undefined reference to `EVP_MD_CTX_destroy'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.01.rcgu.o): In function `openssl::ssl::SslMethod::tls':
          openssl.a5fe216aaa8e965a-cgu.01:(.text._ZN7openssl3ssl9SslMethod3tls17h9c8304f1a28e9117E+0x3): undefined reference to `SSLv23_method'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.01.rcgu.o): In function `openssl::ssl::SSL_CTX_up_ref':
          openssl.a5fe216aaa8e965a-cgu.01:(.text._ZN7openssl3ssl14SSL_CTX_up_ref17hac51fd216a248376E+0x3a): undefined reference to `CRYPTO_add_lock'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.01.rcgu.o): In function `openssl::ssl::get_new_ssl_idx':
          openssl.a5fe216aaa8e965a-cgu.01:(.text._ZN7openssl3ssl15get_new_ssl_idx17h41e8164daa31af54E+0x66): undefined reference to `SSL_get_ex_new_index'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.01.rcgu.o): In function `openssl::ssl::get_new_ssl_idx::{{closure}}':
          openssl.a5fe216aaa8e965a-cgu.01:(.text._ZN7openssl3ssl15get_new_ssl_idx28_$u7b$$u7b$closure$u7d$$u7d$17h55a5303d885c3efeE+0x4a): undefined reference to `SSL_get_ex_new_index'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.05.rcgu.o): In function `openssl::x509::X509_up_ref':
          openssl.a5fe216aaa8e965a-cgu.05:(.text._ZN7openssl4x50911X509_up_ref17h7a7dcb3ecd8c7a19E+0x37): undefined reference to `CRYPTO_add_lock'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.06.rcgu.o): In function `openssl::pkey::EVP_PKEY_up_ref':
          openssl.a5fe216aaa8e965a-cgu.06:(.text._ZN7openssl4pkey15EVP_PKEY_up_ref17hc90de5ba9199de8dE+0x37): undefined reference to `CRYPTO_add_lock'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.09.rcgu.o): In function `openssl::version::number':
          openssl.a5fe216aaa8e965a-cgu.09:(.text._ZN7openssl7version6number17hcfadea7c8d7f4e2aE+0x3): undefined reference to `SSLeay'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.14.rcgu.o): In function `<openssl::sign::Signer as core::ops::drop::Drop>::drop':
          openssl.a5fe216aaa8e965a-cgu.14:(.text._ZN63_$LT$openssl..sign..Signer$u20$as$u20$core..ops..drop..Drop$GT$4drop17h319ad03c68a0b64dE+0x6): undefined reference to `EVP_MD_CTX_destroy'
          /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.14.rcgu.o): In function `<openssl::sign::Verifier as core::ops::drop::Drop>::drop':
          openssl.a5fe216aaa8e965a-cgu.14:(.text._ZN65_$LT$openssl..sign..Verifier$u20$as$u20$core..ops..drop..Drop$GT$4drop17h3eb5cdd692740597E+0x6): undefined reference to `EVP_MD_CTX_destroy'
          /home/maart/git/lemmy/target/debug/deps/libopenssl_sys-65c6ecaf5d9d4223.rlib(openssl_sys-65c6ecaf5d9d4223.openssl_sys.9cda4c51bce7defe-cgu.0.rcgu.o): In function `openssl_sys::openssl::init::{{closure}}':
          openssl_sys.9cda4c51bce7defe-cgu.0:(.text._ZN11openssl_sys7openssl4init28_$u7b$$u7b$closure$u7d$$u7d$17h501316a9d3fa0ab5E+0x12): undefined reference to `SSL_library_init'
          openssl_sys.9cda4c51bce7defe-cgu.0:(.text._ZN11openssl_sys7openssl4init28_$u7b$$u7b$closure$u7d$$u7d$17h501316a9d3fa0ab5E+0x1b): undefined reference to `SSL_load_error_strings'
          openssl_sys.9cda4c51bce7defe-cgu.0:(.text._ZN11openssl_sys7openssl4init28_$u7b$$u7b$closure$u7d$$u7d$17h501316a9d3fa0ab5E+0x24): undefined reference to `OPENSSL_add_all_algorithms_noconf'
          openssl_sys.9cda4c51bce7defe-cgu.0:(.text._ZN11openssl_sys7openssl4init28_$u7b$$u7b$closure$u7d$$u7d$17h501316a9d3fa0ab5E+0x2d): undefined reference to `CRYPTO_num_locks'
          openssl_sys.9cda4c51bce7defe-cgu.0:(.text._ZN11openssl_sys7openssl4init28_$u7b$$u7b$closure$u7d$$u7d$17h501316a9d3fa0ab5E+0x2c2): undefined reference to `CRYPTO_set_locking_callback'
          /home/maart/git/lemmy/target/debug/deps/libopenssl_sys-65c6ecaf5d9d4223.rlib(openssl_sys-65c6ecaf5d9d4223.openssl_sys.9cda4c51bce7defe-cgu.0.rcgu.o): In function `openssl_sys::openssl::init::set_id_callback':
          openssl_sys.9cda4c51bce7defe-cgu.0:(.text._ZN11openssl_sys7openssl4init15set_id_callback17h4a00aa2cfee8b905E+0x12): undefined reference to `CRYPTO_set_id_callback'
          collect2: error: ld returned 1 exit status

### Version

current master

**Comment by MV-GH** [comment]
After upgrading my distro i have now `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)`

Which gives me this error instead

maart/git/lemmy/target/debug/deps/lemmy_server-6c9dda3efb56b29a" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/bin/ld: warning: libssl.so.1.1, needed by /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libpq.so, may conflict with libssl.so.3
          /usr/bin/ld: /home/maart/git/lemmy/target/debug/deps/libopenssl-012159e753d13160.rlib(openssl-012159e753d13160.openssl.a5fe216aaa8e965a-cgu.01.rcgu.o): undefined reference to symbol 'SSL_get_peer_certificate@@OPENSSL_1_1_0'
          /usr/bin/ld: /lib/x86_64-linux-gnu/libssl.so.1.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status

**Comment by MV-GH** [comment]
Can lemmy only be build with OpenSSL 1.0 ??

**Comment by MV-GH** [comment]
cargo clean && cargo build solved it, weird though
